### PR TITLE
READMEs in org-mode + texinfo doc support

### PR DESCRIPTION
**Pull request by guicho271828**
for better readability on github pages.

### CODE REVIEW

**Comment by guicho271828** [comment]
Thanks for merging the pullreq. Although the quality of the ~~docstring~~ doc I made is still insufficient, do you consider adding gf-pages that shows the readme html, and also adding this library to quicklisp?

**Comment by Bike** [comment]
I'm not sure what you mean by gf-pages. I could add this to quicklisp, but I haven't looked at it in months, so I'll probably reacquaint myself and then see about that.

Also, thanks for doing all that. Are you using this library?

**Comment by guicho271828** [comment]
gh-pages is a sort of web hosting by github that can be easily set up by
1. create a branch called gh-pages
2. put index.html in it.

so you just have to create a branch, remove everything but doc/README.html, move it and rename it as index.html. The page will then become available at http://Bike.github.io/compiler-macro/ .

I'm not using this library yet. I made the doc for understanding the API of this library. After the reorganization (put into 1 doc), I finally get to understand how to use it.

**Comment by guicho271828** [comment]
Anyway, cool lib! I'm not using it yet, but have a plan of.

**Comment by guicho271828** [comment]
comment: adding CLOS-like API does not seem particularly important, since we have a good  type-based pattern matching library like optima.

**Pull request merged**
