### PR TITLE
Add redirection for several common special forms.

### PR DESCRIPTION
**Pull request by commander-trashdin**
I'm not sure if that is how it was intended to work, but it works. Feel free to correct me about internal mechanics of this any moment. I'll add more later, it's just that these were very important from the start.

### CODE REVIEW

**Comment by Bike** [comment]
boy, haven't touched this library in a while. Are you using it? For what? I'm curious.

anyway, the type of tagbody is NULL (meaning it returns the value nil), not NIL (meaning it does not return, like with GO up the file). and the TODO probably doesn't need to be in the code.

**Comment by commander-trashdin** [comment]
omg, that's embarassing. that;'s  the second time in my life I switched null to nil. Also, I left todo in there to show future..intentions?

**Comment by commander-trashdin** [comment]
I'm using it for some tinkering in addition to what I try to do for numcl.

**Comment by commander-trashdin** [comment]
I fixed some errors and added more forms. The problem is environment is ignored, which is a big problem for anything inside `let`. I tried to figure out how to fix it, but sbcl's cltl2 impl seems to be sure about just discarding it completely.


P.S. I actually really like what you were doing here, I love this particular area in CS. I'm trying to get into it.

**Comment by commander-trashdin** [comment]
So, are you interested in dealing with this lib?

**Comment by Bike** [comment]
I've more or less given up on it in large part because I've become skeptical of this type inference regime. I think to do meaningful type inference you need to do flow analysis and other operations that are better understood as part of the compiler.

That said, I don't mind merging a PR if it will really help. This one has problems though. These are not valid inferrers for binding forms. For example, say we have `(flet ((foo ...)) (declare (ftype (function * integer) foo)) (bar (macrolet ((foo ...)) ...)))`, and `bar` is a compiler macro that wants to use type information. When it tries to infer the type of the macrolet form, it will ignore the macro definition when examining the body, and so any internal `(foo ...)` forms will be considered to be function calls and treated as returning integers, even though the macro definition is actually unrelated. Maybe this is what you mean by "env has no effect here"?

Also, you misspelled "labels", and you can just do `(or ,(form-type then env) ,(form-type else env))` in `if`.

**Comment by commander-trashdin** [comment]
Oh, I see the problem. But when I said env has no effect however, I meant that literally if you have a let with variable x defined, and you have a whatever declaration about x, and than even just x as the last form, it will give you `t` no matter what.

"Lables" is a big problem for me for some reason, I type it like that 30% of the times. No idea what to do.

Anyway, I see you haven't given up on CL in general, you work on SICL and clasp it seems? I really want to get into static code analysis, especially applied to CL compiler development. This library is just something I stumbled upon, do you have anything better in mind nowadays? Or do you think now type inference in CL is not something one could meaningfully work with?

**Comment by Bike** [comment]
> Oh, I see the problem. But when I said env has no effect however, I meant that literally if you have a let with variable x defined, and you have a whatever declaration about x, and than even just x as the last form, it will give you t no matter what.

Right. Say you do `(form-type '(let ((x (foo))) (declare (type fixnum x)) x) nil)`. This will go through your `let` inferrer, which does `(form-type '(progn (declare (type fixnum x)) x) nil)`. The declaration is ignored by the `progn` inferrer (though, really, shouldn't be there at all, so there's another invalid thing) and you end up with `(form-type 'x nil)`, which returns `T`. Your inferrer just uses the original environment without augmentation, so there is no information available about `x`. Hypothetically, it might be possible to fix this with code to parse declarations and stuff, though I'm not sure CLTL2 `augment-environment` allows augmentation with type declarations off the top of my head.

> This library is just something I stumbled upon, do you have anything better in mind nowadays? Or do you think now type inference in CL is not something one could meaningfully work with?

I don't think what I was attempting here can be done portably, without reimplementing substantial portions of the compiler. CL does not provide enough hooks for programmers to take advantage of any type inference/flow analysis/etc done by the implementation, and it is not obvious to me how those hooks would look in a language extension.

That said, CL implementations do do type inference - they just don't expose an interface like I had in mind with this library. I seem to have neglected it in the readme, but a lot of this library is an attempt at a portable version of SBCL's `sb-c:deftransform`, which allows similar type-based transformations based on SBCL's meaningful type inference.

As it happens, a few people and I are taking another crack at writing a type inference system for SICL now. You're welcome to contribute code or discussion on beach's repo, or the IRC channel on freenode: #sicl. We're attempting to come up with a more modular/comprehensible system than the existing ones, though it's not a language extension.

**Comment by commander-trashdin** [comment]
Right, I was looking at sicl for some time already. I know about sbcl's deftransform, but it does look more like a dispatching mechanism on types in itself, rather than interface that provides some info -- that is, I was unable to find anything about extracting the inferred types from it.

I'm afraid at my level of knowledge I'm mostly unable to contribute anything serious to the compiler development, esp as serious as sicl is. There is also really no way to learn much about any CL compiler internals, except for just straightforward bruteforce dive into code/some manual.
If only there was some sort of internship....

Anyway, I ll go check out irc then I suppose. Maybe I could at least help with testing existing code.
SICL compiles, not interprets, right? How fast/safe it is compared to sbcl? and how ready for usage? (and maybe this q/a should happen somewhere else)

**Comment by Bike** [comment]
> I know about sbcl's deftransform, but it does look more like a dispatching mechanism on types in itself, rather than interface that provides some info -- that is, I was unable to find anything about extracting the inferred types from it.

Part of the point here is that what this library does - provide that information to _compiler macros_ - is not adequate, because compiler macros run too early to get useful type information. A later stage has to be defined to use that information. Without that stage, there's not much point defining an interface.

> I'm afraid at my level of knowledge I'm mostly unable to contribute anything serious to the compiler development, esp as serious as sicl is. There is also really no way to learn much about any CL compiler internals, except for just straightforward bruteforce dive into code/some manual.

It's fine. beach could probably find something for you to do and it's pretty usual to learn as you go with this stuff. Probably we could also recommend you papers/books/etc though.

> SICL compiles, not interprets, right? How fast/safe it is compared to sbcl? and how ready for usage? (and maybe this q/a should happen somewhere else)

Yeah, IRC is probably better for this. SICL itself has only started being able to boot. Cleavir, the compiler, can be used separately, though, which is what Clasp does.

**Pull request closed without merging**
